### ISSUE TITLE
C:\D.Legal\flutter-feed-app-master\flutter-feed-app-master>flutter create .

### ISSUE THREAD

**Issue by sandeepnarula999** [ishaileshmishra/healthnest#2]
C:\D.Legal\flutter-feed-app-master\flutter-feed-app-master>flutter create .
"flutter-feed-app-master" is not a valid Dart package name.

**Comment by ishaileshmishra** [comment]
@sandeepnarula999 Thanks for writing to me, 
The better way to download the repository is like below.
`git clone and URL_path_of_repoisitory`

Avoid downloading the repository by ui.
